### ISSUE TITLE
Implement Design and Storage Strategy for Presentations Post Type

### ISSUE THREAD

**Issue by madrilene** [unlockopen/www.unlockopen.com-v4#38]
## Description
Post type called "presentations" which will require a design and a strategy for storing images used in Open Graph (OG) image creation. This issue aims to outline the requirements and gather input for the best practices on implementation.

## Objectives
1. **Design:**
   - Decide on the Notist data to be used
   - Create a design for the presentations post type, considering their relationship to the conference post type and the speaking post type

3. **Image Storage:**
   - Decide on the best location for storing "raw" images. 
   - Keep on using Notist data as a source or make all contents stored in Eleventy directly?

### Tasks
- [ ] **Design Draft:**
  - [ ] Create design mockups for the presentations post type.
  - [ ] Review and iterate based on feedback.

- [ ] **Implementation:**
  - [ ] Implement the designs in the frontend.
  - [ ] Setup the storage solution for "raw" images.
  - [ ] Integrate with the OG image generation process.
